github: n173sh4d0w # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: n173sh4d0w # Replace with a single Patreon username
liberapay: # Replace with a single Liberapay username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
